export type DummyServiceSlug =
  | "pesawat"
  | "hotel"
  | "kereta"
  | "bus"
  | "kapal"
  | "kapal-pesiar"
  | "aktivitas"

export type DummyCatalogItem = {
  id: string
  title: string
  location: string
  region: string
  group: string
  image: string
  availabilityNote: string
  statusNote: string
  highlights: string[]
  facts: {
    label: string
    value: string
  }[]
}

export type DummyServiceCatalog = {
  slug: DummyServiceSlug
  emptyKeyword: string
  searchPlaceholder: string
  supportHref: string
  promoHref: string
  visualTheme: {
    heroMobileImage: string
    heroDesktopImage: string
    heroOverlayClass: string
    accentBadgeClass: string
    resultPanelClass: string
  }
  uiCopy: {
    id: {
      searchNoun: string
      resultTitle: string
      resultNoun: string
      keywordLabel: string
      regionLabel: string
      groupLabel: string
      locationLabel: string
    }
    en: {
      searchNoun: string
      resultTitle: string
      resultNoun: string
      keywordLabel: string
      regionLabel: string
      groupLabel: string
      locationLabel: string
    }
  }
  items: DummyCatalogItem[]
}

const extraDummyFlightItems: DummyCatalogItem[] = [
  {
    id: "flight-cgk-sub",
    title: "Jakarta - Surabaya Early Shuttle",
    location: "CGK - SUB",
    region: "Domestik",
    group: "Sekali jalan",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy route tambahan untuk uji jalur domestik high-frequency.",
    statusNote: "Cocok untuk validasi search hero ke katalog dengan koridor bisnis pendek.",
    highlights: ["Early wave", "Business shuttle", "Frequent corridor"],
    facts: [
      { label: "Route code", value: "CGK-SUB" },
      { label: "Cabin", value: "Economy" },
      { label: "Window", value: "Morning" },
    ],
  },
  {
    id: "flight-cgk-yia",
    title: "Jakarta - Yogyakarta Weekend Connector",
    location: "CGK - YIA",
    region: "Domestik",
    group: "Pulang pergi",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Contoh route leisure pendek untuk trafik akhir pekan.",
    statusNote: "Bisa dipakai untuk cek round-trip dan filter rute populer domestik.",
    highlights: ["Weekend city break", "Round-trip ready", "Leisure demand"],
    facts: [
      { label: "Route code", value: "CGK-YIA" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Demand", value: "Weekend" },
    ],
  },
  {
    id: "flight-cgk-upg",
    title: "Jakarta - Makassar Network Bridge",
    location: "CGK - UPG",
    region: "Domestik",
    group: "Sekali jalan",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy trunk route untuk pengujian jaringan Indonesia timur.",
    statusNote: "Siap dipakai untuk cek pola domestic trunk dan seat note berbeda.",
    highlights: ["Trunk route", "Eastern network", "Midday departure"],
    facts: [
      { label: "Route code", value: "CGK-UPG" },
      { label: "Cabin", value: "Economy" },
      { label: "Window", value: "Afternoon" },
    ],
  },
  {
    id: "flight-cgk-kno",
    title: "Jakarta - Medan Demand Pulse",
    location: "CGK - KNO",
    region: "Domestik",
    group: "Promo route",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy fare lane untuk contoh traffic Sumatra dengan promo pressure.",
    statusNote: "Membantu tes keyword route dan variasi group promo route.",
    highlights: ["Promo lane", "Sumatra demand", "Economy saver"],
    facts: [
      { label: "Route code", value: "CGK-KNO" },
      { label: "Cabin", value: "Economy" },
      { label: "Demand", value: "High" },
    ],
  },
  {
    id: "flight-sub-dps",
    title: "Surabaya - Bali Leisure Shuttle",
    location: "SUB - DPS",
    region: "Domestik",
    group: "Sekali jalan",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Contoh konektor wisata domestik dengan rotasi tinggi.",
    statusNote: "Cocok untuk uji city pair leisure di luar Jakarta.",
    highlights: ["Leisure shuttle", "Short hop", "Holiday traffic"],
    facts: [
      { label: "Route code", value: "SUB-DPS" },
      { label: "Cabin", value: "Economy" },
      { label: "Pattern", value: "Holiday" },
    ],
  },
  {
    id: "flight-sub-bdj",
    title: "Surabaya - Banjarmasin Connector",
    location: "SUB - BDJ",
    region: "Domestik",
    group: "Business",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy city pair regional dengan kebutuhan corporate menengah.",
    statusNote: "Berguna untuk cek grouping business pada rute domestik sekunder.",
    highlights: ["Regional business", "Corporate mix", "Weekday heavy"],
    facts: [
      { label: "Route code", value: "SUB-BDJ" },
      { label: "Cabin", value: "Business" },
      { label: "Pattern", value: "Weekday" },
    ],
  },
  {
    id: "flight-dps-lbj",
    title: "Bali - Labuan Bajo Island Hop",
    location: "DPS - LBJ",
    region: "Domestik",
    group: "Promo route",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy route wisata premium untuk koridor Bali - Flores.",
    statusNote: "Bagus untuk tes keyword destinasi wisata dan promo seasonal.",
    highlights: ["Island hop", "Scenic route", "Seasonal promo"],
    facts: [
      { label: "Route code", value: "DPS-LBJ" },
      { label: "Cabin", value: "Economy" },
      { label: "Demand", value: "Seasonal" },
    ],
  },
  {
    id: "flight-dps-sub",
    title: "Bali - Surabaya Return Corridor",
    location: "DPS - SUB",
    region: "Domestik",
    group: "Pulang pergi",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy domestic return corridor untuk perjalanan kerja pendek.",
    statusNote: "Bisa dipakai untuk cek return flow non-CGK.",
    highlights: ["Return corridor", "Short business", "Frequent route"],
    facts: [
      { label: "Route code", value: "DPS-SUB" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Use case", value: "Business" },
    ],
  },
  {
    id: "flight-yia-dps",
    title: "Yogyakarta - Bali Holiday Spur",
    location: "YIA - DPS",
    region: "Domestik",
    group: "Sekali jalan",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Contoh spur route leisure dari Jawa ke Bali.",
    statusNote: "Membantu uji keyword bandara kedua dan kombinasi search selain CGK.",
    highlights: ["Holiday spur", "Domestic leisure", "Morning seats"],
    facts: [
      { label: "Route code", value: "YIA-DPS" },
      { label: "Cabin", value: "Economy" },
      { label: "Window", value: "Morning" },
    ],
  },
  {
    id: "flight-upg-bpn",
    title: "Makassar - Balikpapan Energy Route",
    location: "UPG - BPN",
    region: "Domestik",
    group: "Business",
    image: "/home-assets/card-flight.png",
    availabilityNote: "Dummy inter-island corporate lane untuk kebutuhan industri.",
    statusNote: "Cocok untuk menguji koridor business di Indonesia timur.",
    highlights: ["Energy corridor", "Corporate lane", "Short stay"],
    facts: [
      { label: "Route code", value: "UPG-BPN" },
      { label: "Cabin", value: "Business" },
      { label: "Use case", value: "Corporate" },
    ],
  },
  {
    id: "flight-cgk-bkk",
    title: "Jakarta - Bangkok City Escape",
    location: "CGK - BKK",
    region: "Internasional",
    group: "Promo route",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh route Asia Tenggara untuk city-break international.",
    statusNote: "Bagus untuk uji filter internasional dan keyword maskapai/rute.",
    highlights: ["City escape", "SEA traffic", "Promo-friendly"],
    facts: [
      { label: "Route code", value: "CGK-BKK" },
      { label: "Cabin", value: "Economy" },
      { label: "Demand", value: "Leisure" },
    ],
  },
  {
    id: "flight-cgk-kul",
    title: "Jakarta - Kuala Lumpur Regional Bridge",
    location: "CGK - KUL",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy route regional untuk uji business traveler lintas negara.",
    statusNote: "Cocok untuk mengetes search hero menuju pair internasional mainstream.",
    highlights: ["Regional bridge", "Business mix", "Weekday demand"],
    facts: [
      { label: "Route code", value: "CGK-KUL" },
      { label: "Cabin", value: "Business" },
      { label: "Pattern", value: "Weekday" },
    ],
  },
  {
    id: "flight-cgk-hkg",
    title: "Jakarta - Hong Kong Commerce Lane",
    location: "CGK - HKG",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh route bisnis Asia Timur dengan demand reguler.",
    statusNote: "Membantu uji rute komersial dan variasi internasional di katalog.",
    highlights: ["Commerce lane", "East Asia", "Business focus"],
    facts: [
      { label: "Route code", value: "CGK-HKG" },
      { label: "Cabin", value: "Business" },
      { label: "Demand", value: "Regular" },
    ],
  },
  {
    id: "flight-cgk-icn",
    title: "Jakarta - Seoul Trend Route",
    location: "CGK - ICN",
    region: "Internasional",
    group: "Promo route",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy route Korea untuk tes demand leisure internasional.",
    statusNote: "Bagus untuk pencarian keyword rute populer Asia Timur.",
    highlights: ["Korea demand", "Leisure trend", "Promo watch"],
    facts: [
      { label: "Route code", value: "CGK-ICN" },
      { label: "Cabin", value: "Economy" },
      { label: "Trend", value: "High" },
    ],
  },
  {
    id: "flight-cgk-pvg",
    title: "Jakarta - Shanghai Trade Window",
    location: "CGK - PVG",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh route perdagangan untuk traffic enterprise dan supplier visit.",
    statusNote: "Bisa dipakai untuk cek business grouping Asia Timur.",
    highlights: ["Trade window", "Enterprise travel", "East Asia lane"],
    facts: [
      { label: "Route code", value: "CGK-PVG" },
      { label: "Cabin", value: "Business" },
      { label: "Use case", value: "Enterprise" },
    ],
  },
  {
    id: "flight-cgk-syd",
    title: "Jakarta - Sydney Long Haul Base",
    location: "CGK - SYD",
    region: "Internasional",
    group: "Pulang pergi",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy long-haul route untuk kebutuhan return itinerary.",
    statusNote: "Membantu tes alur pulang-pergi di rute internasional jarak jauh.",
    highlights: ["Long haul", "Return focus", "Australia corridor"],
    facts: [
      { label: "Route code", value: "CGK-SYD" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Distance", value: "Long haul" },
    ],
  },
  {
    id: "flight-dps-sin",
    title: "Bali - Singapore Weekend Bridge",
    location: "DPS - SIN",
    region: "Internasional",
    group: "Pulang pergi",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh return route lintas negara untuk weekend travel.",
    statusNote: "Cocok untuk tes pair populer Bali ke Singapura.",
    highlights: ["Weekend bridge", "Short international", "Return ready"],
    facts: [
      { label: "Route code", value: "DPS-SIN" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Demand", value: "Weekend" },
    ],
  },
  {
    id: "flight-dps-mel",
    title: "Bali - Melbourne Seasonal Lift",
    location: "DPS - MEL",
    region: "Internasional",
    group: "Promo route",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy long leisure route untuk musim liburan Australia.",
    statusNote: "Berguna untuk uji keyword destination internasional jarak menengah.",
    highlights: ["Seasonal lift", "Holiday route", "Australia leisure"],
    facts: [
      { label: "Route code", value: "DPS-MEL" },
      { label: "Cabin", value: "Economy" },
      { label: "Season", value: "Holiday" },
    ],
  },
  {
    id: "flight-sub-sin",
    title: "Surabaya - Singapore Trade Connector",
    location: "SUB - SIN",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy pair regional untuk uji search internasional di luar Jakarta.",
    statusNote: "Bagus untuk memastikan homepage hero tidak hanya hidup di CGK.",
    highlights: ["Regional connector", "Trade route", "Business mix"],
    facts: [
      { label: "Route code", value: "SUB-SIN" },
      { label: "Cabin", value: "Business" },
      { label: "Pattern", value: "Weekday" },
    ],
  },
  {
    id: "flight-cgk-hnd-via-sin",
    title: "Jakarta - Tokyo Smart Connector",
    location: "CGK - HND",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy itinerary transit untuk alternatif masuk Tokyo via Singapore.",
    statusNote: "Membantu tes keyword multi-city dan transit di rute Jepang.",
    highlights: ["Via Singapore", "Tokyo access", "Smart connector"],
    facts: [
      { label: "Route code", value: "CGK-SIN-HND" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Singapore" },
    ],
  },
  {
    id: "flight-cgk-kix-via-kul",
    title: "Jakarta - Osaka Connector",
    location: "CGK - KIX",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh itinerary transit untuk masuk Kansai.",
    statusNote: "Cocok untuk pengujian multi-city route ke Jepang barat.",
    highlights: ["Via Kuala Lumpur", "Osaka access", "Multi-city test"],
    facts: [
      { label: "Route code", value: "CGK-KUL-KIX" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Kuala Lumpur" },
    ],
  },
  {
    id: "flight-cgk-pek-via-hkg",
    title: "Jakarta - Beijing East Link",
    location: "CGK - PEK",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy transit route untuk koridor Beijing dengan stop Asia Timur.",
    statusNote: "Bisa dipakai mengetes kombinasi route code transit yang lebih panjang.",
    highlights: ["Via Hong Kong", "Beijing link", "East Asia transit"],
    facts: [
      { label: "Route code", value: "CGK-HKG-PEK" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Hong Kong" },
    ],
  },
  {
    id: "flight-dps-icn-via-sin",
    title: "Bali - Seoul Vacation Connector",
    location: "DPS - ICN",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh transit leisure route Bali ke Korea.",
    statusNote: "Bagus untuk tes multi-city dengan origin non-Jakarta.",
    highlights: ["Vacation connector", "Via Singapore", "Korea leisure"],
    facts: [
      { label: "Route code", value: "DPS-SIN-ICN" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Singapore" },
    ],
  },
  {
    id: "flight-sub-nrt-via-kul",
    title: "Surabaya - Tokyo Kansai Feeder",
    location: "SUB - NRT",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy feeder internasional untuk menguji search hero dari kota kedua.",
    statusNote: "Membantu lihat apakah flow hero ke katalog tetap nyambung untuk pair non-CGK.",
    highlights: ["Secondary city", "Japan feeder", "Transit test"],
    facts: [
      { label: "Route code", value: "SUB-KUL-NRT" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Kuala Lumpur" },
    ],
  },
  {
    id: "flight-cgk-dxb",
    title: "Jakarta - Dubai Premium Corridor",
    location: "CGK - DXB",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh long-haul premium corridor ke Timur Tengah.",
    statusNote: "Cocok untuk menguji traffic enterprise dan premium cabin.",
    highlights: ["Premium corridor", "Middle East", "Long haul"],
    facts: [
      { label: "Route code", value: "CGK-DXB" },
      { label: "Cabin", value: "Business" },
      { label: "Distance", value: "Long haul" },
    ],
  },
  {
    id: "flight-cgk-doh",
    title: "Jakarta - Doha Hub Link",
    location: "CGK - DOH",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy hub route untuk traffic sambungan Timur Tengah.",
    statusNote: "Bagus untuk cek route keyword dan grouping business internasional.",
    highlights: ["Hub link", "Middle East", "Connection-friendly"],
    facts: [
      { label: "Route code", value: "CGK-DOH" },
      { label: "Cabin", value: "Business" },
      { label: "Use case", value: "Hub" },
    ],
  },
  {
    id: "flight-cgk-del",
    title: "Jakarta - Delhi Growth Lane",
    location: "CGK - DEL",
    region: "Internasional",
    group: "Promo route",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh route South Asia untuk memperluas variasi keyword.",
    statusNote: "Membantu uji pair yang lebih niche namun tetap realistis.",
    highlights: ["South Asia", "Growth lane", "Promo watch"],
    facts: [
      { label: "Route code", value: "CGK-DEL" },
      { label: "Cabin", value: "Economy" },
      { label: "Region", value: "South Asia" },
    ],
  },
  {
    id: "flight-cgk-jed",
    title: "Jakarta - Jeddah Faith Corridor",
    location: "CGK - JED",
    region: "Internasional",
    group: "Pulang pergi",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy route Timur Tengah dengan use case religi.",
    statusNote: "Cocok untuk menguji route code long-haul dan pola return khusus.",
    highlights: ["Faith corridor", "Long haul", "Return ready"],
    facts: [
      { label: "Route code", value: "CGK-JED" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Use case", value: "Religious" },
    ],
  },
  {
    id: "flight-cgk-ruh",
    title: "Jakarta - Riyadh Corporate Reach",
    location: "CGK - RUH",
    region: "Internasional",
    group: "Business",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh corporate reach ke Saudi untuk variasi Timur Tengah.",
    statusNote: "Berguna untuk cek hasil search hero di route enterprise long-haul.",
    highlights: ["Corporate reach", "Saudi route", "Business travel"],
    facts: [
      { label: "Route code", value: "CGK-RUH" },
      { label: "Cabin", value: "Business" },
      { label: "Use case", value: "Enterprise" },
    ],
  },
  {
    id: "flight-dps-per",
    title: "Bali - Perth Sun Corridor",
    location: "DPS - PER",
    region: "Internasional",
    group: "Sekali jalan",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy short-haul Australia route dengan pola leisure kuat.",
    statusNote: "Membantu tes keyword route Bali ke Australia barat.",
    highlights: ["Sun corridor", "Australia west", "Leisure flow"],
    facts: [
      { label: "Route code", value: "DPS-PER" },
      { label: "Cabin", value: "Economy" },
      { label: "Demand", value: "Leisure" },
    ],
  },
  {
    id: "flight-dps-bne",
    title: "Bali - Brisbane Holiday Link",
    location: "DPS - BNE",
    region: "Internasional",
    group: "Pulang pergi",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh return link untuk pasar liburan Australia timur.",
    statusNote: "Bagus untuk uji return route internasional dari Bali.",
    highlights: ["Holiday link", "East Australia", "Return demand"],
    facts: [
      { label: "Route code", value: "DPS-BNE" },
      { label: "Trip type", value: "Round-trip" },
      { label: "Pattern", value: "Holiday" },
    ],
  },
  {
    id: "flight-sub-hkg-via-sin",
    title: "Surabaya - Hong Kong Shopper Link",
    location: "SUB - HKG",
    region: "Internasional",
    group: "Multi kota",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Dummy shopper route via Singapore untuk tes search multi-segment.",
    statusNote: "Cocok untuk memastikan query multi-city jalan dari kota selain Jakarta.",
    highlights: ["Shopper link", "Via Singapore", "Secondary origin"],
    facts: [
      { label: "Route code", value: "SUB-SIN-HKG" },
      { label: "Cabin", value: "Economy" },
      { label: "Transit", value: "Singapore" },
    ],
  },
  {
    id: "flight-yia-sin",
    title: "Yogyakarta - Singapore City Pair",
    location: "YIA - SIN",
    region: "Internasional",
    group: "Sekali jalan",
    image: "/home-assets/promo-flight.png",
    availabilityNote: "Contoh pair internasional dari secondary airport Jawa.",
    statusNote: "Bagus untuk lihat apakah hero homepage tetap tersambung di route yang lebih niche.",
    highlights: ["Secondary airport", "City pair", "Regional international"],
    facts: [
      { label: "Route code", value: "YIA-SIN" },
      { label: "Cabin", value: "Economy" },
      { label: "Window", value: "Afternoon" },
    ],
  },
]

const dummyCatalogs: Record<DummyServiceSlug, DummyServiceCatalog> = {
  pesawat: {
    slug: "pesawat",
    emptyKeyword: "rute atau maskapai",
    searchPlaceholder: "Cari rute, kota, atau maskapai dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/hero-bg.png",
      heroDesktopImage: "/home-assets/promo-flight.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(240,248,255,0.96)_0%,rgba(239,246,255,0.88)_30%,rgba(219,234,254,0.45)_60%,rgba(239,246,255,0.1)_100%)]",
      accentBadgeClass: "border-sky-200 bg-sky-50/92 text-sky-700",
      resultPanelClass: "border-sky-100 bg-[linear-gradient(180deg,#f6fbff_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "rute dan maskapai contoh",
        resultTitle: "Hasil katalog rute",
        resultNoun: "rute contoh",
        keywordLabel: "Rute / maskapai",
        regionLabel: "Region terbang",
        groupLabel: "Tipe perjalanan",
        locationLabel: "Kode rute",
      },
      en: {
        searchNoun: "sample routes and airlines",
        resultTitle: "Route catalog results",
        resultNoun: "sample routes",
        keywordLabel: "Route / airline",
        regionLabel: "Flight region",
        groupLabel: "Trip type",
        locationLabel: "Route code",
      },
    },
    items: [
      {
        id: "flight-dps-kul",
        title: "Bali - Kuala Lumpur Leisure Flow",
        location: "DPS - KUL",
        region: "Internasional",
        group: "Promo route",
        image: "/home-assets/promo-flight.png",
        availabilityNote: "Dummy route untuk promo lintas destinasi favorit.",
        statusNote: "Belum live, tapi sudah cocok untuk rule airline, cabin, dan departure window.",
        highlights: ["Weekend peak", "Leisure demand", "Promo-friendly"],
        facts: [
          { label: "Route code", value: "DPS-KUL" },
          { label: "Cabin", value: "Economy" },
          { label: "Demand", value: "Leisure" },
        ],
      },
      ...extraDummyFlightItems,
    ],
  },
  hotel: {
    slug: "hotel",
    emptyKeyword: "kota atau properti",
    searchPlaceholder: "Cari kota, area, atau hotel dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/card-hotel-1.png",
      heroDesktopImage: "/home-assets/promo-hotel.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(255,249,245,0.97)_0%,rgba(255,247,237,0.9)_30%,rgba(254,215,170,0.34)_60%,rgba(255,247,237,0.1)_100%)]",
      accentBadgeClass: "border-amber-200 bg-amber-50/92 text-amber-700",
      resultPanelClass: "border-amber-100 bg-[linear-gradient(180deg,#fffaf2_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "properti dan area contoh",
        resultTitle: "Hasil katalog properti",
        resultNoun: "properti contoh",
        keywordLabel: "Kota / properti",
        regionLabel: "Region menginap",
        groupLabel: "Tipe properti",
        locationLabel: "Area properti",
      },
      en: {
        searchNoun: "sample properties and areas",
        resultTitle: "Property catalog results",
        resultNoun: "sample properties",
        keywordLabel: "City / property",
        regionLabel: "Stay region",
        groupLabel: "Property type",
        locationLabel: "Property area",
      },
    },
    items: [
      {
        id: "hotel-bali-resort",
        title: "Kuta Sunset Resort Collection",
        location: "Kuta, Bali",
        region: "Indonesia",
        group: "Resort",
        image: "/home-assets/card-hotel-1.png",
        availabilityNote: "Contoh katalog hotel leisure dengan city targeting.",
        statusNote: "Belum inventory live, tapi siap untuk city, star rating, check-in, dan durasi inap.",
        highlights: ["4 star", "Family stay", "Beach corridor"],
        facts: [
          { label: "Star", value: "4 star" },
          { label: "Stay cue", value: "Family" },
          { label: "Area", value: "Beach" },
        ],
      },
      {
        id: "hotel-jakarta-business",
        title: "Sudirman Business Stay Hub",
        location: "Jakarta Pusat",
        region: "Indonesia",
        group: "Business hotel",
        image: "/home-assets/card-hotel-2.png",
        availabilityNote: "Dummy properti untuk kebutuhan weekday dan corporate stay.",
        statusNote: "Bisa dipakai untuk menguji nightly stay, payment method targeting, dan hotel city code.",
        highlights: ["Weekday booking", "Business area", "Breakfast included"],
        facts: [
          { label: "Star", value: "4 star" },
          { label: "Stay cue", value: "Business" },
          { label: "Meal", value: "Breakfast" },
        ],
      },
      {
        id: "hotel-singapore-city",
        title: "Marina City Connect Hotel",
        location: "Singapore",
        region: "Asia",
        group: "City hotel",
        image: "/home-assets/promo-hotel.png",
        availabilityNote: "Contoh katalog internasional dengan positioning urban stay.",
        statusNote: "Fondasi hotel-ready untuk country targeting dan stay window lintas negara.",
        highlights: ["5 star", "Urban trip", "Short break"],
        facts: [
          { label: "Star", value: "5 star" },
          { label: "Stay cue", value: "Urban" },
          { label: "Trip", value: "Short break" },
        ],
      },
      {
        id: "hotel-tokyo-compact",
        title: "Shinjuku Compact Stay",
        location: "Tokyo",
        region: "Asia",
        group: "Compact stay",
        image: "/home-assets/card-hotel-2.png",
        availabilityNote: "Dummy unit untuk kebutuhan short stay dan city explorer.",
        statusNote: "Belum live, tetapi struktur checkout hotel nanti bisa memakai shape data yang sama.",
        highlights: ["3 star", "Transit stay", "Metro access"],
        facts: [
          { label: "Star", value: "3 star" },
          { label: "Stay cue", value: "Transit" },
          { label: "Access", value: "Metro" },
        ],
      },
    ],
  },
  kereta: {
    slug: "kereta",
    emptyKeyword: "rute atau layanan",
    searchPlaceholder: "Cari rute atau layanan kereta dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/card-train.png",
      heroDesktopImage: "/home-assets/card-train.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(248,250,252,0.97)_0%,rgba(241,245,249,0.9)_30%,rgba(191,219,254,0.32)_60%,rgba(241,245,249,0.1)_100%)]",
      accentBadgeClass: "border-indigo-200 bg-indigo-50/92 text-indigo-700",
      resultPanelClass: "border-indigo-100 bg-[linear-gradient(180deg,#f8faff_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "jalur dan layanan kereta contoh",
        resultTitle: "Hasil katalog jalur",
        resultNoun: "jalur contoh",
        keywordLabel: "Rute / layanan",
        regionLabel: "Koridor kereta",
        groupLabel: "Jenis layanan",
        locationLabel: "Koridor stasiun",
      },
      en: {
        searchNoun: "sample rail lines and services",
        resultTitle: "Rail catalog results",
        resultNoun: "sample rail lines",
        keywordLabel: "Route / service",
        regionLabel: "Rail corridor",
        groupLabel: "Service type",
        locationLabel: "Station corridor",
      },
    },
    items: [
      {
        id: "train-whoosh-jkt-bdg",
        title: "Jakarta - Bandung Fast Rail Window",
        location: "Halim - Tegalluar",
        region: "Jawa",
        group: "Kereta cepat",
        image: "/home-assets/card-train.png",
        availabilityNote: "Contoh katalog cepat untuk rute high-demand.",
        statusNote: "Belum seat live, cocok untuk fondasi jadwal, kelas, dan promo jalur populer.",
        highlights: ["WHOOSH", "Premium economy", "Same-day trip"],
        facts: [
          { label: "Service", value: "WHOOSH" },
          { label: "Class", value: "Premium" },
          { label: "Pattern", value: "Same-day" },
        ],
      },
      {
        id: "train-gambir-yogya",
        title: "Gambir - Yogyakarta Heritage Line",
        location: "Jakarta - Yogyakarta",
        region: "Jawa",
        group: "Antarkota",
        image: "/home-assets/card-train.png",
        availabilityNote: "Dummy rute klasik untuk long-distance train catalog.",
        statusNote: "Bisa dipakai untuk menyusun layer operator, class targeting, dan departure timing.",
        highlights: ["Night route", "Executive focus", "Leisure mix"],
        facts: [
          { label: "Service", value: "Executive" },
          { label: "Timing", value: "Night" },
          { label: "Use case", value: "Leisure" },
        ],
      },
      {
        id: "train-sby-mlg",
        title: "Surabaya - Malang Regular Shuttle",
        location: "Surabaya - Malang",
        region: "Jawa Timur",
        group: "Komuter",
        image: "/home-assets/card-train.png",
        availabilityNote: "Contoh layanan pendek untuk komuter dan keluarga.",
        statusNote: "Fondasi dummy untuk route regional dan volume transaksi kecil-menengah.",
        highlights: ["Short hop", "Daily repeat", "Budget-friendly"],
        facts: [
          { label: "Service", value: "Commuter" },
          { label: "Pattern", value: "Daily" },
          { label: "Fare cue", value: "Budget" },
        ],
      },
      {
        id: "train-jkt-solo",
        title: "Jakarta - Solo Family Rail Plan",
        location: "Jakarta - Solo",
        region: "Jawa",
        group: "Family route",
        image: "/home-assets/card-train.png",
        availabilityNote: "Dummy jalur keluarga dengan pola liburan.",
        statusNote: "Belum live, namun siap menjadi anchor untuk promo seasonal kereta.",
        highlights: ["Holiday demand", "Family cabin", "Weekend heavy"],
        facts: [
          { label: "Service", value: "Family" },
          { label: "Demand", value: "Holiday" },
          { label: "Pattern", value: "Weekend" },
        ],
      },
    ],
  },
  bus: {
    slug: "bus",
    emptyKeyword: "rute atau operator",
    searchPlaceholder: "Cari rute atau operator bus dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/hero-reference.png",
      heroDesktopImage: "/home-assets/hero-bg.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(247,254,231,0.97)_0%,rgba(236,253,245,0.88)_30%,rgba(134,239,172,0.28)_60%,rgba(236,253,245,0.08)_100%)]",
      accentBadgeClass: "border-emerald-200 bg-emerald-50/92 text-emerald-700",
      resultPanelClass: "border-emerald-100 bg-[linear-gradient(180deg,#f3fff8_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "operator dan koridor bus contoh",
        resultTitle: "Hasil katalog operator",
        resultNoun: "operator contoh",
        keywordLabel: "Rute / operator",
        regionLabel: "Region darat",
        groupLabel: "Tipe layanan",
        locationLabel: "Koridor perjalanan",
      },
      en: {
        searchNoun: "sample bus operators and corridors",
        resultTitle: "Operator catalog results",
        resultNoun: "sample operators",
        keywordLabel: "Route / operator",
        regionLabel: "Ground region",
        groupLabel: "Service type",
        locationLabel: "Travel corridor",
      },
    },
    items: [
      {
        id: "bus-jkt-bdg",
        title: "Jakarta - Bandung Express Sleeper",
        location: "Jakarta - Bandung",
        region: "Jawa Barat",
        group: "Sleeper",
        image: "/home-assets/hero-bg.png",
        availabilityNote: "Contoh katalog sleeper dan premium coach.",
        statusNote: "Belum operator live, siap untuk fondasi jadwal, operator, dan rute.",
        highlights: ["Sleeper seat", "Night route", "High frequency"],
        facts: [
          { label: "Operator cue", value: "Sleeper" },
          { label: "Timing", value: "Night" },
          { label: "Pattern", value: "Frequent" },
        ],
      },
      {
        id: "bus-sby-yk",
        title: "Surabaya - Yogyakarta Intercity",
        location: "Surabaya - Yogyakarta",
        region: "Jawa",
        group: "Antarkota",
        image: "/home-assets/hero-reference.png",
        availabilityNote: "Dummy operator antarkota untuk contoh route map.",
        statusNote: "Cocok untuk pengujian harga operator, pickup point, dan waktu berangkat.",
        highlights: ["Pickup point", "Mid-tier fare", "Student demand"],
        facts: [
          { label: "Operator cue", value: "Intercity" },
          { label: "Fare cue", value: "Mid-tier" },
          { label: "Audience", value: "Student" },
        ],
      },
      {
        id: "bus-medan-aceh",
        title: "Medan - Banda Aceh Corridor",
        location: "Medan - Banda Aceh",
        region: "Sumatra",
        group: "Lintas provinsi",
        image: "/home-assets/hero-bg.png",
        availabilityNote: "Contoh lintas provinsi untuk ekspansi beyond Jawa.",
        statusNote: "Belum live, tetapi struktur katalog dummy ini siap untuk operator regional.",
        highlights: ["Long haul", "Regional operator", "Overnight"],
        facts: [
          { label: "Operator cue", value: "Regional" },
          { label: "Trip", value: "Long haul" },
          { label: "Pattern", value: "Overnight" },
        ],
      },
      {
        id: "bus-bali-labuanbajo",
        title: "Bali Overland Connector",
        location: "Denpasar - Labuan Bajo",
        region: "Nusa Tenggara",
        group: "Travel combo",
        image: "/home-assets/dest-labuanbajo.png",
        availabilityNote: "Dummy travel combo untuk rute wisata.",
        statusNote: "Berguna untuk menguji packaging bus + aktivitas pada tahap berikutnya.",
        highlights: ["Travel combo", "Leisure route", "Seasonal"],
        facts: [
          { label: "Operator cue", value: "Travel combo" },
          { label: "Route style", value: "Leisure" },
          { label: "Season", value: "Peak" },
        ],
      },
    ],
  },
  kapal: {
    slug: "kapal",
    emptyKeyword: "pelabuhan atau rute",
    searchPlaceholder: "Cari pelabuhan atau rute kapal dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/hero-reference.png",
      heroDesktopImage: "/home-assets/dest-singapore.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(239,248,255,0.97)_0%,rgba(224,242,254,0.9)_30%,rgba(125,211,252,0.3)_60%,rgba(224,242,254,0.08)_100%)]",
      accentBadgeClass: "border-cyan-200 bg-cyan-50/92 text-cyan-700",
      resultPanelClass: "border-cyan-100 bg-[linear-gradient(180deg,#f2fcff_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "pelabuhan dan rute laut contoh",
        resultTitle: "Hasil katalog pelayaran",
        resultNoun: "pelayaran contoh",
        keywordLabel: "Pelabuhan / rute",
        regionLabel: "Region laut",
        groupLabel: "Tipe pelayaran",
        locationLabel: "Koridor pelabuhan",
      },
      en: {
        searchNoun: "sample ports and sea routes",
        resultTitle: "Sailing catalog results",
        resultNoun: "sample sailings",
        keywordLabel: "Port / route",
        regionLabel: "Sea region",
        groupLabel: "Sailing type",
        locationLabel: "Port corridor",
      },
    },
    items: [
      {
        id: "ship-merak-bakauheni",
        title: "Merak - Bakauheni Fast Ferry Flow",
        location: "Banten - Lampung",
        region: "Selat Sunda",
        group: "Fast ferry",
        image: "/home-assets/hero-reference.png",
        availabilityNote: "Contoh katalog penyeberangan ramai dengan pola harian.",
        statusNote: "Belum live, tapi siap untuk struktur pelabuhan, trip window, dan operator.",
        highlights: ["Daily crossing", "Vehicle-ready", "Peak holiday"],
        facts: [
          { label: "Port mode", value: "Fast ferry" },
          { label: "Vehicle", value: "Ready" },
          { label: "Pattern", value: "Daily" },
        ],
      },
      {
        id: "ship-bali-lombok",
        title: "Padang Bai - Senggigi Sea Link",
        location: "Bali - Lombok",
        region: "Nusa Tenggara",
        group: "Leisure ferry",
        image: "/home-assets/dest-bali.png",
        availabilityNote: "Dummy rute wisata bahari untuk perjalanan pendek.",
        statusNote: "Cocok menjadi dasar promo regional dan penargetan musim liburan.",
        highlights: ["Short crossing", "Tourist route", "Weekend demand"],
        facts: [
          { label: "Port mode", value: "Leisure ferry" },
          { label: "Trip", value: "Short" },
          { label: "Demand", value: "Weekend" },
        ],
      },
      {
        id: "ship-surabaya-makassar",
        title: "Surabaya - Makassar Regular Sea Route",
        location: "Surabaya - Makassar",
        region: "Antarpulau",
        group: "Kapal laut",
        image: "/home-assets/hero-bg.png",
        availabilityNote: "Contoh rute jarak jauh untuk katalog antarpulau.",
        statusNote: "Belum ticketing live, siap untuk fondasi jadwal multi-day dan cabin basic.",
        highlights: ["Long haul", "Cabin mix", "Logistics corridor"],
        facts: [
          { label: "Port mode", value: "Sea route" },
          { label: "Cabin", value: "Basic mix" },
          { label: "Trip", value: "Multi-day" },
        ],
      },
      {
        id: "ship-batam-bintan",
        title: "Batam - Bintan Island Shuttle",
        location: "Batam - Bintan",
        region: "Kepulauan Riau",
        group: "Island shuttle",
        image: "/home-assets/dest-singapore.png",
        availabilityNote: "Dummy island shuttle untuk kebutuhan short transfer.",
        statusNote: "Berguna untuk fondasi transfer harbor dan opsi multi-operator.",
        highlights: ["Short transfer", "Island hop", "Frequent departure"],
        facts: [
          { label: "Port mode", value: "Island shuttle" },
          { label: "Transfer", value: "Short" },
          { label: "Pattern", value: "Frequent" },
        ],
      },
    ],
  },
  "kapal-pesiar": {
    slug: "kapal-pesiar",
    emptyKeyword: "itinerary atau pelayaran",
    searchPlaceholder: "Cari itinerary cruise dummy",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/hero-header-background-1.jpg",
      heroDesktopImage: "/home-assets/hero-header-background-1.jpg",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(255,247,250,0.96)_0%,rgba(253,242,248,0.88)_30%,rgba(244,114,182,0.22)_60%,rgba(253,242,248,0.08)_100%)]",
      accentBadgeClass: "border-rose-200 bg-rose-50/92 text-rose-700",
      resultPanelClass: "border-rose-100 bg-[linear-gradient(180deg,#fff5f9_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "itinerary dan cabin cruise contoh",
        resultTitle: "Hasil katalog itinerary",
        resultNoun: "itinerary contoh",
        keywordLabel: "Itinerary / cruise",
        regionLabel: "Region pelayaran",
        groupLabel: "Tipe cruise",
        locationLabel: "Jalur itinerary",
      },
      en: {
        searchNoun: "sample cruise itineraries and cabins",
        resultTitle: "Itinerary catalog results",
        resultNoun: "sample itineraries",
        keywordLabel: "Itinerary / cruise",
        regionLabel: "Sailing region",
        groupLabel: "Cruise type",
        locationLabel: "Itinerary route",
      },
    },
    items: [
      {
        id: "cruise-singapore-penang",
        title: "Singapore - Penang Weekend Cruise",
        location: "Singapore - Penang",
        region: "Asia Tenggara",
        group: "Weekend cruise",
        image: "/home-assets/dest-singapore.png",
        availabilityNote: "Contoh itinerary pendek untuk premium leisure.",
        statusNote: "Belum live, tetapi siap untuk cabin class, sail date, dan promo seasonal.",
        highlights: ["3D2N", "Balcony mix", "Weekend getaway"],
        facts: [
          { label: "Nights", value: "3D2N" },
          { label: "Cabin", value: "Balcony" },
          { label: "Style", value: "Weekend" },
        ],
      },
      {
        id: "cruise-bali-komodo",
        title: "Bali - Komodo Scenic Voyage",
        location: "Bali - Labuan Bajo",
        region: "Indonesia",
        group: "Scenic cruise",
        image: "/home-assets/dest-labuanbajo.png",
        availabilityNote: "Dummy itinerary premium untuk jalur wisata unggulan.",
        statusNote: "Bisa jadi fondasi paket hybrid cruise + aktivitas pada fase berikutnya.",
        highlights: ["Luxury route", "Island view", "Premium cabin"],
        facts: [
          { label: "Nights", value: "4D3N" },
          { label: "Cabin", value: "Premium" },
          { label: "Style", value: "Scenic" },
        ],
      },
      {
        id: "cruise-shanghai-okinawa",
        title: "Shanghai - Okinawa Seasonal Sailing",
        location: "Shanghai - Okinawa",
        region: "Asia Timur",
        group: "Seasonal",
        image: "/home-assets/hero-header-background-1.jpg",
        availabilityNote: "Contoh itinerary lintas negara untuk cruise seasonal.",
        statusNote: "Belum live, cocok untuk promosi window-based dan cabin targeting.",
        highlights: ["Seasonal run", "International", "Family cruise"],
        facts: [
          { label: "Nights", value: "5D4N" },
          { label: "Cabin", value: "Family" },
          { label: "Style", value: "Seasonal" },
        ],
      },
      {
        id: "cruise-japan-spring",
        title: "Japan Spring Blossom Cruise",
        location: "Tokyo - Osaka",
        region: "Jepang",
        group: "Theme cruise",
        image: "/home-assets/dest-tokyo.png",
        availabilityNote: "Dummy thematic sailing untuk promosi kalender musiman.",
        statusNote: "Berguna untuk menguji landing premium dan summary itinerary multi-stop.",
        highlights: ["Cherry season", "Multi-stop", "Premium positioning"],
        facts: [
          { label: "Nights", value: "6D5N" },
          { label: "Cabin", value: "Premium" },
          { label: "Style", value: "Theme" },
        ],
      },
    ],
  },
  aktivitas: {
    slug: "aktivitas",
    emptyKeyword: "aktivitas atau destinasi",
    searchPlaceholder: "Cari aktivitas dummy atau destinasi",
    supportHref: "/bantuan",
    promoHref: "/promo",
    visualTheme: {
      heroMobileImage: "/home-assets/dest-bali.png",
      heroDesktopImage: "/home-assets/dest-bangkok.png",
      heroOverlayClass:
        "bg-[linear-gradient(90deg,rgba(255,251,235,0.97)_0%,rgba(255,247,237,0.88)_30%,rgba(251,191,36,0.26)_60%,rgba(255,247,237,0.08)_100%)]",
      accentBadgeClass: "border-orange-200 bg-orange-50/92 text-orange-700",
      resultPanelClass: "border-orange-100 bg-[linear-gradient(180deg,#fff8f1_0%,#ffffff_100%)]",
    },
    uiCopy: {
      id: {
        searchNoun: "atraksi dan aktivitas contoh",
        resultTitle: "Hasil katalog aktivitas",
        resultNoun: "aktivitas contoh",
        keywordLabel: "Aktivitas / destinasi",
        regionLabel: "Region pengalaman",
        groupLabel: "Tipe aktivitas",
        locationLabel: "Lokasi aktivitas",
      },
      en: {
        searchNoun: "sample attractions and activities",
        resultTitle: "Activity catalog results",
        resultNoun: "sample activities",
        keywordLabel: "Activity / destination",
        regionLabel: "Experience region",
        groupLabel: "Activity type",
        locationLabel: "Activity location",
      },
    },
    items: [
      {
        id: "activity-bali-atv",
        title: "Bali ATV Jungle Pass",
        location: "Ubud, Bali",
        region: "Indonesia",
        group: "Outdoor",
        image: "/home-assets/dest-bali.png",
        availabilityNote: "Contoh katalog atraksi luar ruang dengan voucher flow.",
        statusNote: "Belum voucher live, siap untuk fondasi instant redeem dan date window.",
        highlights: ["Outdoor", "Voucher-ready", "Half-day"],
        facts: [
          { label: "Voucher", value: "Ready" },
          { label: "Duration", value: "Half-day" },
          { label: "Mode", value: "Outdoor" },
        ],
      },
      {
        id: "activity-jakarta-observatory",
        title: "Jakarta City Observatory Entry",
        location: "Jakarta",
        region: "Indonesia",
        group: "City experience",
        image: "/home-assets/dest-jakarta.png",
        availabilityNote: "Dummy tiket atraksi urban untuk city break.",
        statusNote: "Cocok untuk penargetan date slot, quota per user, dan promo kode.",
        highlights: ["Urban attraction", "Timed entry", "Family-friendly"],
        facts: [
          { label: "Voucher", value: "Timed entry" },
          { label: "Audience", value: "Family" },
          { label: "Mode", value: "City" },
        ],
      },
      {
        id: "activity-bangkok-food-tour",
        title: "Bangkok Night Food Walk",
        location: "Bangkok",
        region: "Asia",
        group: "Guided tour",
        image: "/home-assets/dest-bangkok.png",
        availabilityNote: "Contoh aktivitas terkurasi untuk short guided tour.",
        statusNote: "Belum live, tetapi shape data dummy ini siap untuk supplier aktivitas nanti.",
        highlights: ["Night tour", "Guide included", "Small group"],
        facts: [
          { label: "Voucher", value: "Guide-included" },
          { label: "Duration", value: "Evening" },
          { label: "Mode", value: "Small group" },
        ],
      },
      {
        id: "activity-tokyo-pass",
        title: "Tokyo Urban Multi-Attraction Pass",
        location: "Tokyo",
        region: "Asia",
        group: "Multi-pass",
        image: "/home-assets/dest-tokyo.png",
        availabilityNote: "Dummy city pass untuk use case voucher multi-visit.",
        statusNote: "Siap menjadi dasar katalog aktivitas instan setelah supplier live disambungkan.",
        highlights: ["City pass", "Multi-entry", "Traveler favorite"],
        facts: [
          { label: "Voucher", value: "Multi-entry" },
          { label: "Duration", value: "Flexible" },
          { label: "Mode", value: "City pass" },
        ],
      },
    ],
  },
}

export function getDummyServiceCatalog(slug: DummyServiceSlug) {
  return dummyCatalogs[slug]
}
